project:
  type: website

website:
  site-url: yevgenryeznik.github.io/personal-page
  title: "Yevgen Ryeznik"
  description: "Yevgen Ryeznik's personal page."
  navbar:
    # background: "#47a7ce"
    right:
      - href: cv.qmd
        text: CV
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - href: teaching.qmd
        text: Teaching
      - href: https://www.linkedin.com/in/yevgen-ryeznik-3975b645/
        text: "{{< fa brands linkedin >}}"
      - href: https://github.com/yevgenryeznik
        text: "{{< fa brands github >}}"
      - href: https://orcid.org/0000-0003-2997-8566
        text: "{{< fa brands orcid >}}"
      - href: https://scholar.google.com/citations?user=9bSyqvMAAAAJ&hl=en&oi=ao
        text: "{{< ai google-scholar >}}"
  page-footer: "&copy; Yevgen Ryeznik (2022)"
format:
  html:
    theme: theme.scss
    toc: true

editor: visual

