---
title: Publications (2004 -- 2021)
site: distill::distill_website
---

### DOCTORAL THESIS

1. **Ryeznik, Y.** (2019) “Optimal Adaptive Designs and Adaptive Randomization Techniques for Clinical Trials”, _Uppsala Dissertations in Mathematics_, ISSN 1401-2049, **113**, p. 94. http://uu.diva-portal.org/smash/record.jsf?pid=diva2%3A1291159&dswid=8852

### PEER-REVIEWED PUBLICATIONS IN STATISTICAL AND MATHEMATICAL JOURNALS

1.	**Ryeznik, Y.**, Sverdlov, O., Svensson, E., Montepiedra, G., Hooker, A., Wong, W.K. (2021) ”Pharmacometrics Meets Statistics – A Synergy for Modern Drug Development”, CPT: Pharmacometrics & System Pharmacology. _**Under review**_.

1.	Fei, Z., **Ryeznik, Y.**, Sverdlov, O., Tan, Ch. W., Wong, W. K., (2021) "A Selective Survey of Data Science Applications for Healthcare Diagnosis, Inference, and Pandemic Response", IEEE Transactions on Big Data. _**Under review**_.

1.	Svedlov, O., **Ryeznik, Y.**, Wong W.K. (2021) "Imbalance Randomization (Rationales for)", _Wiley StatsRef_: Statistical References Online. _**Submitted**_. 

1.	Berger V., Bour L.,  Carter K.,  Chipman J..,  Everett C.,  Heussen N.,  Hewitt C., Hilgers R.-D.,  Luo Y.A., Renteria J.,  **Ryeznik Y.**,  Sverdlov O.,  Uschner D. (2021) "A roadmap to using randomization techniques in clinical trials", BMC Medical Research Methodology, _**accepted**_. https://doi.org/10.21203/rs.3.rs-135735/v1

1. Sverdlov, O., **Ryeznik, Y.**, Wong W. K. (2021) "Opportunity for efficiency in clinical development: An overview of adaptive clinical trial designs and innovative machine learning tools, with examples from the cardiovascular field", _Contemporary Clinical Trials_. **105(5)**. https://doi.org/10.1016/j.cct.2021.106397 

1. Sverdlov, O., **Ryeznik, Y.**, Wong W. K. (2020) “On Optimal Designs for Multi-Objective Clinical Trials: An Updated Review”, _Journal of Statistical Theory and Practice_, **14 (10)**. https://doi.org/10.1007/s42519-019-0073-4

1. Tyzhnenko, A. G., **Ryeznik, Y.** (2019) “Ordinary Least Squares: the Adequacy of Linear Regression Solutions under Multicollinearity and without It”, _The Problems of Economy_, **1**, pp. 217-227. https://doi.org/10.32983/2222-0712-2019-1-217-227

1. Sverdlov, O., **Ryeznik, Y.** (2019) “Implementing Unequal Randomization in Clinical Trials with Heterogeneous Tretament Cost”, _Statistics in Medicine_, **38 (16)**, pp. 2905-2927. https://doi.org/10.1002/sim.8160

1. **Ryeznik, Y.**, Sverdlov, O., Hooker, A. C. (2018) "Implementing Optimal Designs for Dose–Response Studies Through Adaptive Randomization for a Small Population Group", _The AAPS journal_ **20 (85)**. https://doi.org/10.1208/s12248-018-0242-5

1. **Ryeznik Y.**, Sverdlov, O. (2018) "A Comparative Study of Restricted Randomization Procedures for Multi-Arm Trials with Equal or Unequal Treatment Allocation Ratios", _Statistics in Medicine_ **37(21)**, pp. 3056-3077. https://doi.org/10.1002/sim.7817

1. **Ryeznik, Y.**, Sverdlov, O., Hooker, A. C. (2018) "Adaptive Optimal Designs for Dose-Finding Studies with Time-to-Event Outcomes", _The AAPS journal_ **20 (24)**.  https://doi.org/10.1208/s12248-017-0166-5
    
1. **Ryeznik, Y.**, Sverdlov, O., Wong W. K. (2015) "RARtool: A MATLAB Software Package for Designing Response-Adaptive Randomized Clinical Trials with Time-to-Event Outcomes", _Journal of statistical software_ **66 (1)**. https://doi.org/10.18637/jss.v066.i01

1. Sverdlov, O., **Ryeznik, Y.**, Wu, Sh. (2015) "Exact Bayesian inference comparing binomial proportions, with application to proof-of-concept clinical trials", _Therapeutic Innovation \& Regulatory Science_ **49 (1)**, pp. 163-174. https://doi.org/10.1177/2168479014547420
    
1. Sverdlov, O., **Ryeznik, Y.**, Wong, W. K. (2014) "Efficient and Ethical Response-Adaptive Randomization Designs for Multi-Arm Clinical Trials with Weibull Time-to-Event Outcomes", _Journal of Biopharmaceutical Statistics_ **24 (4)**, pp. 732-754. https://doi.org/10.1080/10543406.2014.903261
    
1. Sverdlov, O., Wong, W. K., **Ryeznik, Y.** (2014) "Adaptive clinical trial designs for phase I cancer studies." _Statistics Surveys_ **8**, pp. 2-44. https://doi.org/10.1214/14-SS106

1. Sverdlov, O., Rosenberger, W. F., **Ryeznik, Y.** (2013) "Utility of covariate-adjusted response-adaptive randomization in survival trials." _Statistics in Biopharmaceutical Research_ **5 (1)**, pp. 38-53. https://doi.org/10.1080/19466315.2012.754376

1. Sverdlov, O., **Ryeznik, Y.**, Wong, W. K. (2012) "Doubly-adaptive biased coin designs for balancing competing objectives in time-to-event trials" _Statistics and Its Interface_ **5 (4)**, pp. 401-413. https://doi.org/10.4310/SII.2012.v5.n4.a3 

1. Tyzhnenko, A. G., **Ryeznik, Y.** (2010) "Peculiarities of electromagnetic wave scattering from water surface causing an anomalous effect" _Telecommunications and Radio Engineering_ **69 (6)**, pp. 531-536. https://doi.org/10.1615/TelecomRadEng.v69.i6.70

1. **Ryeznik, Y.**, Sukharevsky O. I., Tyzhnenko, A. G. (2008) "Detection of the scatterer's form and size with multyfrequency radiolocation" _The Bulletin of Kharkov National University_ **834**, pp. 31--36. http://www-radiovestnik.univer.kharkov.ua/full/80.pdf (in Russian)
    
1. Tyzhnenko, A. G., **Ryeznik Y.** (2008) "Potentially unbreacable ciphering on a hybrid physical-mathematical level", _The Bulletin of Kharkov National University_ **834**, pp. 108-113. http://www-radiovestnik.univer.kharkov.ua/full/92.pdf
    
1. Tyzhnenko, A. G., **Ryeznik, Y.** (2008) "Identification and localization of reflected pulses under strong noise" _The Bulletin of Kharkov National University_ **806**, pp. 70-74. http://www-radiovestnik.univer.kharkov.ua/full/67.pdf (in Russian). 
    
1. Tyzhnenko, A. G., **Ryeznik, Y.** (2007) "Scattering from sea surface leading spike effect" _Radiotechnics_ **149**, pp. 27-31. (in Russian).

1. Tyzhnenko, A. G., **Ryeznik, Y.** (2007) "Estimation of accuracy of scattering field for 2D screens
calculated with Method of Moments (MoM) in $L_2$" _The Bulletin of Kharkov National University_ **756**, pp. 65-70. http://www-radiovestnik.univer.kharkov.ua/1.php?nom=756 (in Russian)

1. Tyzhnenko, A. G., **Ryeznik, Y.** (2007) "Estimates of accuracy and efficiency of a MoM algorithm in $L_2$ for 2-D screens" _Progress in Electromagnetics Research_ **71**, pp. 295-316. https://doi.org/10.2528/PIER07030603
    
1. Tyzhnenko, A. G., **Ryeznik, Y.** (2007) "Galerkin method solution as a reference solution for MoM algorithms in $L_2$ for $E$-screens", _Journal of Applied Electromagnetism_ *9(1)*, pp. 27-44. Available for download at http://jae.ece.ntua.gr/archive/
    
1. Tyzhnenko, A. G., **Ryeznik, Y.** (2005) "Convergent Galerkin MoM solution for 2-D H-scattering
from screens'' _Electromagnetics_ **25 (4)**, pp. 329-341. https://doi.org/10.1080/02726340590936176
    
1. Tyzhnenko, A. G., **Ryeznik, Y.** (2004) "Convergent Galerkin MoM solution to the hypersingular $1^{st}$ kind integral equation for 2-D Neumann problem" _Journal of Applied Elecromagnetism_ **6 (2)**, pp. 37-51. Available for download at http://jae.ece.ntua.gr/archive/


### PEER-REVIEWED CONFERENCE PROCEEDINGS

1. Tyzhnenko, A. G., **Ryeznik, Y.** (2007) "Scattering amplitude error analysis for the MoM schemes in $L_2$ commonly used for solving a 2-D scattering from screens" _The Sixth International Kharkov Symposium on Millimeter and Submillimeter Waves, MSMW-07_, pp. 319-321, Kharkiv, Ukraine. https://doi.org/10.1109/MSMW.2007.4294648
    
1. Tyzhnenko, A. G., **Ryeznik, Y.** (2006) "A new insight into a possible spike mechanism" _International Conference on Mathematical Methods in Electromagnetics Theory, MMET-06_, pp. 170-172,
Kharkiv, Ukraine. https://doi.org/10.1109/MMET.2006.1689734
     
1. Tyzhnenko, A. G., **Ryeznik, Y.** (2005) "A unique solution for $H$-scattering from 2-D roughness on a PEC plane" _18th International Conference on Applied Electromagnetic, ICECom-05_, pp. 1-4, Dubrovnik,
Croatia. https://doi.org/10.1109/ICECOM.2005.205032


### CO-AUTHORED CONFERENCE PRESENTATIONS

1. "Adaptive dose finding for time-to-event outcomes with adaptive choice of patient number based on response rate" (with O. Sverdlov and A. C. Hooker). _PAGE Meeting_, Lisboa, Portugal, June 7-10, 2016. Slides available online at https://www.page-meeting.org/pdf_assets/5629-[07-JUNE-2016]%20PAGE2016_Main.pdf

1. "Adaptive Optimal Designs for Dose-Finding Studies with Time-to-Event Outcomes on Continuous Dose Space" (with O. Sverdlov and A. C. Hooker). _SIAM Conference on Uncertainty Quantification_, Lausanne, Switzerland, April 5-8, 2016. Abstract available online at http://meetings.siam.org/sess/dsp_talk.cfm?p=75159

1. "Adaptive designs for dose finding clinical trials with time-to-event outcomes" (with O. Sverdlov and A. C. Hooker). _PAGE Meeting_, Hersonissos, Crete, Greece, June 2-5, 2015. Poster available online at https://www.page-meeting.org/pdf_assets/3298-YR_PAGE_2015_Poster_Final.pdf
    
1. "Development of software for simulation and implementation of response-adaptive time-to-event trials" (with O. Sverdlov and W. K. Wong). _Joint Statistical Meetings (JSM)_, San Diego CA, July 28-August 2, 2012. Abstract available online at http://www.amstat.org/meetings/jsm/2012/onlineprogram/AbstractDetails.cfm?abstractid=304097
    
1. "Efficient and ethical adaptive randomization designs for multi-armed clinical trials with Weibull time-to-event outcomes" (with O. Sverdlov and W. K. Wong). _The 20th Applied Statistics Symposium, International Chinese Statistical Association (ICSA)_, New York City, June 26-29, 2011. Program and abstract available online at http://www.icsa.org/2011/online_files/abstractsBook.pdf
    
1. "Covariate-adjusted response-adaptive randomization designs for phase III survival trials" (with O. Sverdlov). _XVII Biostatistics Applied Symposium (BASS)_, Hilton Head, SC, 2010. Slides available online at http://bass.georgiasouthern.edu/PDFs/BASS_2010_Alex_Sverdlov.pdf


### BOOKS AND TUTORIALS:

1. Sverdlov, O., **Ryeznik, Y.** (2021) "Randomization, Stratification, and Outcome Adaptive Allocation" in Handbook of Statistical Methods for Randomized Clinical Trials. Chapman and Hall/CRC.

1. Malyarets, L. M., **Ryeznik, Y.**, Sinkevych, B. V. (2013) "Modern optimization techniques in MatLab. Part II", practice tutorial, Kharkov National University of Economics, 356 pages. (in Ukrainian).
    
1. Malyarets, L. M., **Ryeznik, Y.**, Sinkevych, B. V. (2011) "Modern optimization techniques in MatLab. Part I", practice tutorial, Kharkov National University of Economics, 360 pages. (in Ukrainian)
    
1. Vietlugina, I. V., Dubovyk, K. M., Kaydash, M. V., Mysyura, Y. Y., **Ryeznik, Y. V.**, Sylichova, T. V. (2009) "Mathematics for economists with MatLab", laboratory practice tutorial, Kharkov National University of Economics, 220 pages. (in Ukrainian)
    
1. Malyarets, L. M., **Ryeznik, Y. V.**, Tyzhnenko, A. G. (2008) "Mathematics for economists using MatLab", tutorial, Kharkov National University of Economics, 210 pages. (in Ukrainian)
    
1. Tyzhnenko, A. G., **Ryeznik, Y. V.** (2007) "Methodical recommendations to implementation scientific research on higher mathematics using MatLab", Kharkov National University of Economics, 116 pages. (in Ukrainian)
    
1. **Ryeznik, Y. V.** (2006) "Practical training on higher mathematics using MatLab", chapters 1-3, Kharkov National University of Economics, 192 pages. (in Ukrainian).

